### PR TITLE
Add Nirvana Discography Icons.

### PR DESCRIPTION
**Pull request by brassmonke2**
I don't know if this would work, but if it does.

### CODE REVIEW

**Comment by EliteAsian123** [comment]
Hi, thanks for the PR!

As for the icon, it unfortunately does not follow the [style guidelines](https://github.com/YARC-Official/OpenSource#-guidelines-for-making-icons). Please recreate the icon with the template, and then it can be reviewed by an artist.

As for the `.json`, there's an extra empty set of `{}` at the bottom. Removing these lines should do:
```diff
...
      "icon": "deltaom3ga",
      "type": "charter"
    },
    {
      "ids": [ "nirvanasp" ],
      "names": {
        "en-US": "Nirvana Discography"
      },
      "icon": "nirvana",
      "type": "custom"
+   }
-   },
-   {
-    
-   }
  ]
}
```

**Comment by brassmonke2** [comment]
hopefully this works

**Comment by brassmonke2** [comment]
sorry, this should be the last time

**Review by kaduwaengertner — CHANGES_REQUESTED** [review]
I'll leave the .json part to Elite

The source icon still doesn't fit our guidelines, the Nirvana Icon should not touch the outside circle, also the icon have a lot of sharp pixels on it, needs to be smoother and keep the same color for the lines

**Comment by brassmonke2** [comment]
> I'll leave the .json part to Elite
> 
> The source icon still doesn't fit our guidelines, the Nirvana Icon should not touch the outside circle, also the icon have a lot of sharp pixels on it, needs to be smoother and keep the same color for the lines

Ok, Can I use the smiley or no?

**Comment by brassmonke2** [comment]
alright, it should be fixed now.

**Comment by brassmonke2** [comment]
made it transparent

**Comment by EliteAsian123** [comment]
Hello!

Unfortunately, your `.json` file is still not in the correct format. You're using spaces instead of tabs, and there are still extra brackets. [Here's](https://github.com/YARC-Official/OpenSource/files/13064142/index.json) a corrected version that you can use instead.

As for the icon, it still has unwanted black edges:
image
Here's a reference image for what it should look like:
image

Once these are fixed, you're good to go!

**Comment by brassmonke2** [comment]
[https://imgur.com/a/1homHRv](url)

Would this be good?

**Comment by brassmonke2** [comment]
i think i am good to go

**Comment by brassmonke2** [comment]
I fixed the JSON and the icon is transparent. We are good to go!

**Pull request closed without merging**
