### PR TITLE
Fixes gradient issue

### PR DESCRIPTION
**Pull request by yoitsOJ**
I messed up the gradient in the Djent Hero and Paradigm icons, It's hard to notice at first but in-game it causes some minor artifacting. This should fix that.

### CODE REVIEW

**Comment by EliteAsian123** [comment]
The changes in this PR seem a little messed up. Did you sync your fork before making changes?

**Comment by yoitsOJ** [comment]
> The changes in this PR seem a little messed up. Did you sync your fork before making changes?

I think? I just hit "fetch origin" which is what I thought that was

**Comment by EliteAsian123** [comment]
Still seems to be messed up. For example, line 445 in `extra/index.json` is this in master:
image
But in the PR it's:
image
Not to worry though, I'll merge these changes for you in a bit!

**Comment by yoitsOJ** [comment]
That's really odd, I haven't edited the json since my first commit.

Thanks though, I'll look out for the merge and as far as my fork I'll see if anything got messed up on my end.

**Comment by EliteAsian123** [comment]
No problem! I've merged this for you in the commit above.

On GitHub I believe there should be a "Sync Fork" button that should potentially solve the issue
image

**Comment by yoitsOJ** [comment]
> On GitHub I believe there should be a "Sync Fork" button that should potentially solve the issue

Just synced the fork and re-pulled, everything looks good now. Thanks!

**Pull request closed without merging**
