### PR TITLE
Fortnite Source

### PR DESCRIPTION
**Pull request by Branflake05**
Added a Fortnite source since the game has nearly 300 songs and all the charts are unique (I think?)

### CODE REVIEW

**Comment by EliteAsian123** [comment]
Hello, thank you for the PR!

Unfortunately, we've already decided in the past not to include an FNF icon as it is a very new game and could create some legal risk. Due to this, we aren't going to allow an FNF icon for the time-being. Sorry for the inconvenience.

**Comment by Branflake05** [comment]
Ahh I see, I hadn’t even considered that. Is there any way for me to add it to my own client for myself so that it doesn’t use the default download icon? As I would prefer that just so that everything looks neat

**Comment by EliteAsian123** [comment]
Unfortunately not at the moment because the icons get replaced with the newest version from this repo at the moment. In the future, we'll probably allow custom icon lists! Sorry for the inconvenience.

**Comment by Branflake05** [comment]
No worries at all! Thanks for everything and keep making this game great :)

**Pull request closed without merging**
