### PR TITLE
Add Nirvana Discography Icon

### PR DESCRIPTION
**Pull request by brassmonke2**
I remade it so you don't have to add 17 commits.

### CODE REVIEW

**Comment by EliteAsian123** [comment]
Hello, sorry for the late response! The PR is good by me, just gotta get a final art check from Kadu.

**Comment by brassmonke2** [comment]
nice.

**Comment by kaduwaengertner** [comment]
hey, not on my computer right now but I'll take a look on it tonight, screen too small to properly check anything lol

**Comment by brassmonke2** [comment]
> hey, not on my computer right now but I'll take a look on it tonight, screen too small to properly check anything lol

alright

**Review by kaduwaengertner — APPROVED** [review]

**Pull request merged**
